/**
 * eAdventure is a research project of the
 *    e-UCM research group.
 *
 *    Copyright 2005-2014 e-UCM research group.
 *
 *    You can access a list of all the contributors to eAdventure at:
 *          http://e-adventure.e-ucm.es/contributors
 *
 *    e-UCM is a research group of the Department of Software Engineering
 *          and Artificial Intelligence at the Complutense University of Madrid
 *          (School of Computer Science).
 *
 *          CL Profesor Jose Garcia Santesmases 9,
 *          28040 Madrid (Madrid), Spain.
 *
 *          For more info please visit:  <http://e-adventure.e-ucm.es> or
 *          <http://www.e-ucm.es>
 *
 * ****************************************************************************
 *
 *  This file is part of eAdventure
 *
 *      eAdventure is free software: you can redistribute it and/or modify
 *      it under the terms of the GNU Lesser General Public License as published by
 *      the Free Software Foundation, either version 3 of the License, or
 *      (at your option) any later version.
 *
 *      eAdventure is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU Lesser General Public License for more details.
 *
 *      You should have received a copy of the GNU Lesser General Public License
 *      along with eAdventure.  If not, see <http://www.gnu.org/licenses/>.
 */
package es.eucm.ead.buildtools;

import com.badlogic.gdx.Files;
import com.badlogic.gdx.backends.lwjgl.LwjglFiles;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.utils.Json;
import com.badlogic.gdx.utils.JsonValue;

/**
 * Creates a class with a public static string for each property in
 * repoelement.json. Useful for use in mokap-backend.
 * 
 * Created by jtorrente on 8/12/14.
 */
public class GenerateRepoFields {

	private static final String REPOELEMENT_PATH = "build-tools/generators/src/main/resources/schema/editor/components/repo/repoelement.json";

	private static final String REPOELEMENTFIELDS_PACKAGE = "es.eucm.ead.schemax.repo";

	private static final String REPOELEMENTFIELDS_CLASSNAME = "RepoElementFields";

	private static final String REPOELEMENT_FIELDS_DESTFOLDER = "editor/schema/src/main/java/";

	public static void main(String[] args) {
		System.out.println("Generating RepoElementFields class ...");

		// Parse repoelement.json and generate class code
		System.out.println("Creating class code");
		String classCode = getClassHeader();
		Files files = new LwjglFiles();
		FileHandle fh = files.internal(REPOELEMENT_PATH);
		Json json = new Json();
		JsonValue next = json.fromJson(null, null, fh);
		next = next.child();
		while ((next = next.next()) != null) {
			if (next.name().equals("properties")) {
				JsonValue nextProperty = next.child();
				while (nextProperty != null) {
					// Look for description
					JsonValue description = nextProperty.child();
					while (description != null
							&& !description.name().equals("description")) {
						description = description.next();
					}
					if (description != null) {
						classCode += "\t/**\n";
						classCode += "\t *" + description.asString() + "\n";
						classCode += "\t*/\n";
					}
					classCode += "\tpublic static final String "
							+ nextProperty.name().toUpperCase() + " = \""
							+ nextProperty.name() + "\";\n\n";
					nextProperty = nextProperty.next();
				}
				break;
			}
		}
		classCode += "}";

		// Write to destiny dir
		System.out.println("Writing class to output folder...");
		FileHandle destDir = new FileHandle(files.internal(
				REPOELEMENT_FIELDS_DESTFOLDER
						+ REPOELEMENTFIELDS_PACKAGE.replaceAll("\\.", "/")
						+ "/").file());
		destDir.mkdirs();
		FileHandle destFile = destDir.child(REPOELEMENTFIELDS_CLASSNAME
				+ ".java");
		if (destFile.exists()) {
			destFile.delete();
		}
		destFile.writeString(classCode, false, "UTF-8");
	}

	private static String getClassHeader() {
		return "package "
				+ REPOELEMENTFIELDS_PACKAGE
				+ ";\n"
				+ "\n"
				+ "/**\n"
				+ " * Utility class for referring to fields in class RepoElement.\n"
				+ " * Useful to protect backend from changes in RepoElement api.\n"
				+ " * Autogenerated through Maven.\n" + " */\n"
				+ "public class " + REPOELEMENTFIELDS_CLASSNAME + "{\n";
	}
}
